### ISSUE TITLE
If module is disabled plugins return nothing instead of $result

### ISSUE THREAD

**Issue by leonhardtjo** [devcccc/magento2-address-validation#3]
Hi,
we added the module ("version": "1.3.23") and saw that our payment methods are failing.
`The "array" value's type is invalid. The "int" type was expected. Verify and try again.`

After some debugging we saw that you dont return the $result in the following plugins - if the module is not enabled:
`!$this->configProvider->isEnabled()`

Can you fix it up in the following conditions?
`devcccc/magento2-address-validation/Plugin/SaveValidationResultToQuoteCustomer.php:36`
`devcccc/magento2-address-validation/Plugin/SaveValidationResultToQuote.php:36`

**Comment by 4ctobias** [comment]
Fixed in v.1.3.24 - now $result is returned in all cases.
